/**
 * Script to seed services data to Convex
 * Run with: bun run scripts/seed-services.ts
 */

import { ConvexHttpClient } from "convex/browser";
import { api } from "../convex/_generated/api";

// Services data from YAML files - organized by brand per CLAUDE.md mapping
const servicesData = [
  // ========================================
  // SANKOFA - Marketing & Web Development
  // ========================================

  // Website Development Packages
  {
    brand: "Sankofa" as const,
    name: "Essential Website Package",
    description: "5-7 professional pages with basic SEO setup and contact form. Ideal for local businesses and consultants with a small digital footprint.",
    price: "$1,200 - $2,000",
    priceValue: 1200,
    tags: ["Website", "SEO", "Small Business"],
    status: "active" as const,
    stripeSynced: false,
    category: "website",
  },
  {
    brand: "Sankofa" as const,
    name: "Professional Website Package",
    description: "10-15 custom pages with CMS for blog/news, advanced SEO & analytics, and social feed integration. Includes 60 days priority support.",
    price: "$2,800 - $4,500",
    priceValue: 2800,
    tags: ["Website", "CMS", "SEO", "Analytics"],
    status: "active" as const,
    stripeSynced: false,
    category: "website",
  },
  {
    brand: "Sankofa" as const,
    name: "Business Growth Website Package",
    description: "20-30 pages with complex architecture, custom forms & CRM integration, performance optimization. For platforms requiring e-commerce, membership, or custom workflows.",
    price: "$5,500 - $8,500",
    priceValue: 5500,
    tags: ["Website", "E-commerce", "Enterprise", "Custom API"],
    status: "active" as const,
    stripeSynced: false,
    category: "website",
  },
  {
    brand: "Sankofa" as const,
    name: "Website Maintenance & Updates",
    description: "Ongoing website maintenance, security updates, content changes, and technical support.",
    price: "$100 - $300",
    priceValue: 100,
    priceSuffix: "/month",
    tags: ["Maintenance", "Support"],
    status: "active" as const,
    stripeSynced: false,
    category: "website",
  },
  {
    brand: "Sankofa" as const,
    name: "Content Writing & Copywriting",
    description: "Professional copywriting services for website pages, landing pages, and marketing content.",
    price: "$400 - $1,200",
    priceValue: 400,
    tags: ["Content", "Copywriting"],
    status: "active" as const,
    stripeSynced: false,
    category: "marketing",
  },

  // Social Media Marketing Packages
  {
    brand: "Sankofa" as const,
    name: "Social Media Starter Package",
    description: "4 platforms managed with 12 original posts (graphics + copy), scheduling & optimization, and monthly analytics report. Perfect for maintaining presence.",
    price: "$750 - $1,000",
    priceValue: 750,
    priceSuffix: "/month",
    tags: ["Social Media", "Marketing", "Small Business"],
    status: "active" as const,
    stripeSynced: false,
    category: "social-media",
  },
  {
    brand: "Sankofa" as const,
    name: "Social Media Growth Package",
    description: "4 platforms managed with 20 original posts, weekly Reels/Shorts, and community management. Includes bi-weekly strategy calls.",
    price: "$1,500 - $2,200",
    priceValue: 1500,
    priceSuffix: "/month",
    tags: ["Social Media", "Reels", "Community"],
    status: "active" as const,
    stripeSynced: false,
    category: "social-media",
  },
  {
    brand: "Sankofa" as const,
    name: "Full Service Social Package",
    description: "Unlimited platforms with 40+ original posts, custom video content, and dedicated account manager. Includes paid ads management, influencer outreach, and crisis management.",
    price: "$3,000 - $5,000",
    priceValue: 3000,
    priceSuffix: "/month",
    tags: ["Social Media", "Enterprise", "Paid Ads", "Influencer"],
    status: "active" as const,
    stripeSynced: false,
    category: "social-media",
  },
  {
    brand: "Sankofa" as const,
    name: "Paid Ads Management",
    description: "Professional management of paid advertising campaigns across social platforms. Ad spend not included.",
    price: "$500 - $1,000",
    priceValue: 500,
    priceSuffix: "/month",
    tags: ["Paid Ads", "Marketing"],
    status: "active" as const,
    stripeSynced: false,
    category: "marketing",
  },
  {
    brand: "Sankofa" as const,
    name: "Influencer Campaign",
    description: "Strategic influencer outreach and campaign management to amplify your brand reach.",
    price: "$1,000 - $3,000",
    priceValue: 1000,
    tags: ["Influencer", "Marketing"],
    status: "active" as const,
    stripeSynced: false,
    category: "marketing",
  },
  {
    brand: "Sankofa" as const,
    name: "Social Media Audit",
    description: "Comprehensive analysis of your social media presence with actionable recommendations.",
    price: "$300 - $500",
    priceValue: 300,
    tags: ["Audit", "Strategy"],
    status: "active" as const,
    stripeSynced: false,
    category: "marketing",
  },
  {
    brand: "Sankofa" as const,
    name: "Content Photoshoot",
    description: "Professional photography session for social media content creation.",
    price: "$400 - $800",
    priceValue: 400,
    tags: ["Photography", "Content"],
    status: "active" as const,
    stripeSynced: false,
    category: "photography",
  },

  // ========================================
  // LIGHTHOUSE - Video & Post-Production
  // ========================================

  {
    brand: "Lighthouse" as const,
    name: "Essential Video Package",
    description: "Up to 2 minutes final edit with single location shoot, basic color grading, and 1 week delivery. Perfect for social media content.",
    price: "$800 - $1,500",
    priceValue: 800,
    tags: ["Video", "Social Media", "Small Business"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Professional Video Package",
    description: "Up to 5 minutes final edit with multi-location shoot, professional color grading, and licensed music. Includes 2 revision rounds.",
    price: "$2,000 - $4,000",
    priceValue: 2000,
    tags: ["Video", "Multi-Location", "Professional"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Full Production Package",
    description: "Up to 15 minutes final edit with multi-day production, drone & specialty shots, and full post-production suite. For commercials and documentaries.",
    price: "$5,000 - $10,000",
    priceValue: 5000,
    tags: ["Video", "Commercial", "Documentary", "Drone"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Drone/Aerial Footage Add-On",
    description: "Professional aerial footage using licensed drone equipment for stunning perspectives.",
    price: "$300 - $600",
    priceValue: 300,
    tags: ["Drone", "Aerial", "Video"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Same-Day Highlight Reel",
    description: "Quick turnaround highlight video delivered same day for events and launches.",
    price: "$500 - $800",
    priceValue: 500,
    tags: ["Video", "Events", "Rush"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Raw Footage Package",
    description: "All raw footage from your shoot delivered for your own editing or archive.",
    price: "$200 - $400",
    priceValue: 200,
    tags: ["Video", "Raw", "Archive"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Additional Revision Round",
    description: "Extra round of revisions beyond the package inclusion.",
    price: "$150",
    priceValue: 150,
    priceSuffix: "/round",
    tags: ["Video", "Revision"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Lighthouse" as const,
    name: "Launch Bundle",
    description: "5-7 page website plus up to 2 min promo video with basic SEO setup and social-ready video cuts. Save ~$500 vs. booking separately.",
    price: "$2,300 - $3,000",
    priceValue: 2300,
    tags: ["Bundle", "Website", "Video", "Launch"],
    status: "active" as const,
    stripeSynced: false,
    category: "bundle",
  },
  {
    brand: "Lighthouse" as const,
    name: "Professional Bundle",
    description: "10-15 page custom website plus up to 5 min brand video with CMS + blog setup and multi-location video shoot. Save ~$1,100 vs. booking separately.",
    price: "$5,500 - $7,500",
    priceValue: 5500,
    tags: ["Bundle", "Website", "Video", "CMS"],
    status: "active" as const,
    stripeSynced: false,
    category: "bundle",
  },
  {
    brand: "Lighthouse" as const,
    name: "Premium Bundle",
    description: "20-30 page website + e-commerce plus up to 15 min video production with multi-day shoot, aerial footage, and 90 days priority support.",
    price: "$11,500 - $16,000",
    priceValue: 11500,
    tags: ["Bundle", "E-commerce", "Commercial", "Drone"],
    status: "active" as const,
    stripeSynced: false,
    category: "bundle",
  },
  {
    brand: "Lighthouse" as const,
    name: "Additional Video Cuts",
    description: "Extra video cuts in 15, 30, or 60 second formats for social media and ads.",
    price: "$200 - $400",
    priceValue: 200,
    priceSuffix: "/each",
    tags: ["Video", "Social Media", "Ads"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },

  // ========================================
  // GFAM MEDIA STUDIOS - Podcasts & Studio
  // ========================================

  {
    brand: "GFAM Media Studios" as const,
    name: "Single Angle Basic Podcast",
    description: "60-minute studio recording session with single camera angle and basic editing. Ideal for 30-45 minute finished episodes. Perfect for solo creators.",
    price: "$150",
    priceValue: 150,
    priceSuffix: "/episode",
    tags: ["Podcast", "Basic", "Solo"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Multi-Angle Podcast Production",
    description: "90-minute studio recording with multiple camera angles, professional audio, and real-time camera switching. Ideal for 45-60 minute finished episodes.",
    price: "$225",
    priceValue: 225,
    priceSuffix: "/episode",
    tags: ["Podcast", "Multi-Cam", "Interview"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Premium Multi-Angle Podcast",
    description: "90-minute session with multi-angle + live switching, advanced editing, motion graphics, captions, guest photos, and priority 48-hour delivery.",
    price: "$300",
    priceValue: 300,
    priceSuffix: "/episode",
    tags: ["Podcast", "Premium", "Motion Graphics"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "2-Hour Studio Session",
    description: "90 minutes recording time (plus 30 min setup), engineer/producer, multi-camera setup, and basic post-production editing. Ideal for 45-60 minute episodes.",
    price: "$225",
    priceValue: 225,
    tags: ["Studio", "Rental", "Podcast"],
    status: "active" as const,
    stripeSynced: false,
    category: "studio-rental",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "4-Hour Studio Session",
    description: "Up to 3.5 hours recording time (plus 30 min setup), engineer/producer, multi-camera setup, and premium post-production. For longer content or multiple guests.",
    price: "$400",
    priceValue: 400,
    tags: ["Studio", "Rental", "Extended"],
    status: "active" as const,
    stripeSynced: false,
    category: "studio-rental",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Additional Recording Time (30 min)",
    description: "Extend your recording session by 30 minutes.",
    price: "$50",
    priceValue: 50,
    tags: ["Add-On", "Recording"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Additional Recording Time (15 min)",
    description: "Extend your recording session by 15 minutes.",
    price: "$25",
    priceValue: 25,
    tags: ["Add-On", "Recording"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Virtual Guest Setup",
    description: "Technical setup and management for remote guests joining via video call.",
    price: "$20",
    priceValue: 20,
    priceSuffix: "/guest",
    tags: ["Add-On", "Virtual", "Remote"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "BTS Photography (30 min)",
    description: "Behind-the-scenes photography during your recording session.",
    price: "$60",
    priceValue: 60,
    tags: ["Photography", "BTS"],
    status: "active" as const,
    stripeSynced: false,
    category: "photography",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "BTS Photography (1 hour)",
    description: "Extended behind-the-scenes photography coverage.",
    price: "$120",
    priceValue: 120,
    tags: ["Photography", "BTS"],
    status: "active" as const,
    stripeSynced: false,
    category: "photography",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Guest Photo Capture",
    description: "Professional headshots and photos of guests during the session.",
    price: "$25",
    priceValue: 25,
    tags: ["Photography", "Headshots"],
    status: "active" as const,
    stripeSynced: false,
    category: "photography",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "ISO Video Recordings",
    description: "Individual isolated camera feeds delivered separately for your own editing.",
    price: "$50",
    priceValue: 50,
    tags: ["Video", "ISO", "Raw"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Same-Day Booking",
    description: "Book a studio session for same-day or next-day based on availability.",
    price: "$40",
    priceValue: 40,
    tags: ["Add-On", "Rush"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Social Media Clip Package",
    description: "Short-form clips optimized for social media platforms from your episode.",
    price: "$50",
    priceValue: 50,
    tags: ["Social Media", "Clips"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Highlight Reel",
    description: "Curated highlight video showcasing the best moments of your episode.",
    price: "$75",
    priceValue: 75,
    tags: ["Video", "Highlights"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Custom Thumbnails",
    description: "Professional custom thumbnails for YouTube and podcast platforms.",
    price: "$18",
    priceValue: 18,
    priceSuffix: "/each",
    tags: ["Design", "Thumbnails"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Multi-Platform Upload",
    description: "Distribution of your episode to multiple podcast and video platforms.",
    price: "$40",
    priceValue: 40,
    tags: ["Distribution", "Upload"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Animated Intro/Outro",
    description: "Custom animated intro and outro for your podcast brand.",
    price: "$100",
    priceValue: 100,
    tags: ["Animation", "Branding"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "4K Editing",
    description: "Upgrade to 4K resolution for your final video output.",
    price: "$40",
    priceValue: 40,
    tags: ["4K", "Video"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Color Correction/Grading",
    description: "Basic color correction and grading for consistent, polished look.",
    price: "$55",
    priceValue: 55,
    tags: ["Color", "Post-Production"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Advanced Color Grading",
    description: "Cinematic color grading for premium visual quality.",
    price: "$135",
    priceValue: 135,
    tags: ["Color", "Cinematic"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Audio Enhancement",
    description: "Professional audio enhancement including noise reduction and clarity improvements.",
    price: "$40",
    priceValue: 40,
    tags: ["Audio", "Enhancement"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Monthly Retainer (4 episodes)",
    description: "4 episodes per month with priority scheduling, consistent delivery dates, and dedicated project manager. 15% OFF regular pricing.",
    price: "15% OFF",
    priceValue: 765,
    priceSuffix: "/month",
    tags: ["Package", "Retainer", "Discount"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Season Package (10+ episodes)",
    description: "10+ episodes with brand consistency, bulk delivery options, and free revisions included. 20% OFF regular pricing.",
    price: "20% OFF",
    priceValue: 1800,
    tags: ["Package", "Season", "Discount"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
  {
    brand: "GFAM Media Studios" as const,
    name: "Full-Service Podcast Bundle",
    description: "Multi-angle editing + live switching, social media clips, custom thumbnails, guest photos, multi-platform distribution, and audio enhancement. $438 value.",
    price: "$365",
    priceValue: 365,
    priceSuffix: "/episode",
    tags: ["Bundle", "Full-Service", "Value"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },

  // ========================================
  // CENTEX - Sports & Live Production
  // ========================================

  {
    brand: "Centex" as const,
    name: "Live Event Streaming",
    description: "Professional live streaming for events, conferences, and special broadcasts. Includes travel within 50 miles, setup, and multi-platform streaming.",
    price: "$450",
    priceValue: 450,
    priceSuffix: "/event",
    tags: ["Live", "Streaming", "Events"],
    status: "active" as const,
    stripeSynced: false,
    category: "streaming",
  },
  {
    brand: "Centex" as const,
    name: "Sports Live Stream - Basic",
    description: "Single-camera live stream production for local sports events with basic graphics and commentary setup.",
    price: "$800",
    priceValue: 800,
    priceSuffix: "/event",
    tags: ["Sports", "Live", "Streaming"],
    status: "active" as const,
    stripeSynced: false,
    category: "streaming",
  },
  {
    brand: "Centex" as const,
    name: "Sports Live Stream - Multi-Cam",
    description: "Multi-camera live stream production with real-time switching, professional graphics, and replay capabilities.",
    price: "$1,500",
    priceValue: 1500,
    priceSuffix: "/event",
    tags: ["Sports", "Live", "Multi-Cam"],
    status: "active" as const,
    stripeSynced: false,
    category: "streaming",
  },
  {
    brand: "Centex" as const,
    name: "Full Broadcast Production",
    description: "Complete broadcast production for live sporting events with commentary, graphics, replays, and multi-platform distribution.",
    price: "$3,000 - $8,000",
    priceValue: 3000,
    priceSuffix: "/event",
    tags: ["Broadcast", "Sports", "Full Production"],
    status: "active" as const,
    stripeSynced: false,
    category: "streaming",
  },
  {
    brand: "Centex" as const,
    name: "Sports Highlight Reel",
    description: "Custom highlight video with graphics, music, and branded elements from your event footage.",
    price: "$800 - $1,500",
    priceValue: 800,
    tags: ["Sports", "Highlights", "Video"],
    status: "active" as const,
    stripeSynced: false,
    category: "video",
  },
  {
    brand: "Centex" as const,
    name: "Sports Podcast Production",
    description: "Full podcast production for sports content including recording, editing, and distribution.",
    price: "$350",
    priceValue: 350,
    priceSuffix: "/episode",
    tags: ["Sports", "Podcast"],
    status: "active" as const,
    stripeSynced: false,
    category: "podcast",
  },
];

async function main() {
  // Get the Convex URL from environment
  const convexUrl = process.env.CONVEX_URL || process.env.NEXT_PUBLIC_CONVEX_URL;

  if (!convexUrl) {
    console.error("❌ CONVEX_URL or NEXT_PUBLIC_CONVEX_URL not found in environment");
    console.log("Make sure you have a .env.local file with NEXT_PUBLIC_CONVEX_URL set");
    process.exit(1);
  }

  console.log("🚀 Starting Convex seed...");
  console.log(`📍 Convex URL: ${convexUrl}`);
  console.log(`📦 Services to seed: ${servicesData.length}`);

  const client = new ConvexHttpClient(convexUrl);

  try {
    const result = await client.mutation(api.seed.seedServices, {
      services: servicesData,
      clearExisting: true,
    });

    console.log("✅ Seed completed successfully!");
    console.log(`   Inserted: ${result.inserted} services`);
    console.log(`   Message: ${result.message}`);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

main();
